# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, Ui_ChatWindow):
        Ui_ChatWindow.setObjectName("MainWindow")
        Ui_ChatWindow.resize(1084, 663)
        self.centralwidget = QtWidgets.QWidget(Ui_ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setStyleSheet("""
            QListWidget {
                font: 75 16pt "MS Shell Dlg 2";
            }
            """
        )
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.add_contact_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_contact_btn.setObjectName("add_contact_btn")
        self.verticalLayout.addWidget(self.add_contact_btn)
        self.delete_contact_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_contact_btn.setObjectName("delete_contact_btn")
        self.verticalLayout.addWidget(self.delete_contact_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 0, 781, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msg_list = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.msg_list.setObjectName("msg_list")
        self.verticalLayout_2.addWidget(self.msg_list)
        self.send_msg_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.send_msg_edit.setGeometry(QtCore.QRect(310, 570, 681, 51))
        self.send_msg_edit.setObjectName("textEdit")
        self.send_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_msg_btn.setGeometry(QtCore.QRect(1000, 572, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.send_msg_btn.setFont(font)
        self.send_msg_btn.setObjectName("send_msg_btn")
        Ui_ChatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_ChatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 21))
        self.menubar.setObjectName("menubar")
        Ui_ChatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_ChatWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_ChatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_ChatWindow)

    def retranslateUi(self, Ui_ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_ChatWindow.setWindowTitle(_translate("ChatWindow", "MainWindow"))
        self.add_contact_btn.setText(_translate("Ui_ChatWindow", "Add contact"))
        self.delete_contact_btn.setText(_translate("Ui_ChatWindow", "Delete contact"))
        self.send_msg_btn.setText(_translate("Ui_ChatWindow", "Send"))
